

[package]
edition = "2018"
name = "rust"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dsalgo = "0.3.0"
# cargo-udeps = "*"
# cargo-equip = "0.19.0"
lazy_static = "*"
once_cell = "*"
rand = "*"
